var jsi_8h =
[
    [ "facebook::jsi::Buffer", "classfacebook_1_1jsi_1_1Buffer.html", "classfacebook_1_1jsi_1_1Buffer" ],
    [ "facebook::jsi::StringBuffer", "classfacebook_1_1jsi_1_1StringBuffer.html", "classfacebook_1_1jsi_1_1StringBuffer" ],
    [ "facebook::jsi::MutableBuffer", "classfacebook_1_1jsi_1_1MutableBuffer.html", "classfacebook_1_1jsi_1_1MutableBuffer" ],
    [ "facebook::jsi::PreparedJavaScript", "classfacebook_1_1jsi_1_1PreparedJavaScript.html", "classfacebook_1_1jsi_1_1PreparedJavaScript" ],
    [ "facebook::jsi::HostObject", "classfacebook_1_1jsi_1_1HostObject.html", "classfacebook_1_1jsi_1_1HostObject" ],
    [ "facebook::jsi::NativeState", "classfacebook_1_1jsi_1_1NativeState.html", "classfacebook_1_1jsi_1_1NativeState" ],
    [ "facebook::jsi::Runtime", "classfacebook_1_1jsi_1_1Runtime.html", "classfacebook_1_1jsi_1_1Runtime" ],
    [ "facebook::jsi::Runtime::PointerValue", "structfacebook_1_1jsi_1_1Runtime_1_1PointerValue.html", "structfacebook_1_1jsi_1_1Runtime_1_1PointerValue" ],
    [ "facebook::jsi::Pointer", "classfacebook_1_1jsi_1_1Pointer.html", "classfacebook_1_1jsi_1_1Pointer" ],
    [ "facebook::jsi::PropNameID", "classfacebook_1_1jsi_1_1PropNameID.html", "classfacebook_1_1jsi_1_1PropNameID" ],
    [ "facebook::jsi::Symbol", "classfacebook_1_1jsi_1_1Symbol.html", "classfacebook_1_1jsi_1_1Symbol" ],
    [ "facebook::jsi::BigInt", "classfacebook_1_1jsi_1_1BigInt.html", "classfacebook_1_1jsi_1_1BigInt" ],
    [ "facebook::jsi::String", "classfacebook_1_1jsi_1_1String.html", "classfacebook_1_1jsi_1_1String" ],
    [ "facebook::jsi::Object", "classfacebook_1_1jsi_1_1Object.html", "classfacebook_1_1jsi_1_1Object" ],
    [ "facebook::jsi::WeakObject", "classfacebook_1_1jsi_1_1WeakObject.html", "classfacebook_1_1jsi_1_1WeakObject" ],
    [ "facebook::jsi::Array", "classfacebook_1_1jsi_1_1Array.html", "classfacebook_1_1jsi_1_1Array" ],
    [ "facebook::jsi::ArrayBuffer", "classfacebook_1_1jsi_1_1ArrayBuffer.html", "classfacebook_1_1jsi_1_1ArrayBuffer" ],
    [ "facebook::jsi::Function", "classfacebook_1_1jsi_1_1Function.html", "classfacebook_1_1jsi_1_1Function" ],
    [ "facebook::jsi::Value", "classfacebook_1_1jsi_1_1Value.html", "classfacebook_1_1jsi_1_1Value" ],
    [ "facebook::jsi::Scope", "classfacebook_1_1jsi_1_1Scope.html", "classfacebook_1_1jsi_1_1Scope" ],
    [ "facebook::jsi::JSIException", "classfacebook_1_1jsi_1_1JSIException.html", "classfacebook_1_1jsi_1_1JSIException" ],
    [ "facebook::jsi::JSINativeException", "classfacebook_1_1jsi_1_1JSINativeException.html", "classfacebook_1_1jsi_1_1JSINativeException" ],
    [ "facebook::jsi::JSError", "classfacebook_1_1jsi_1_1JSError.html", "classfacebook_1_1jsi_1_1JSError" ],
    [ "JSI_EXPORT", "jsi_8h.html#a03f972b9e6d24f88a61d7e979eacef0b", null ],
    [ "HostFunctionType", "jsi_8h.html#ab5bd20ade17e509b20d790798c07e83e", null ]
];