name: Deploy Doxygen Documentation

on:
  push:
    branches: [ main ]  # or your default branch
  workflow_dispatch:    # allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-documentation:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: 'recursive'  # Fetches all submodules recursively

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Generate Doxygen Documentation
      run: doxygen

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'generated/html'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
